version: '3'

x-db-img: &db-img
  image: postgres:15-alpine

x-search-img: &search-img
  image: kunansy/tracker_search:6.2.12

x-backup-img: &backup-img
  image: kunansy/fast-backup:0.5.2

x-cache-img: &cache-img
  image: redis:7.2-alpine

x-tracker-img: &tracker-img
  image: kunansy/reading_tracker:2.23.7

x-prometheus-img: &prometheus-img
  image: prom/prometheus:2.48

x-grafana-img: &grafana-img
  image: grafana/grafana:10.0

services:
  tracker-db:
    <<: *db-img
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - database-volume:/var/lib/postgresql/data
    container_name: tracker-db
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    networks:
       - tracker-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}", "-q", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3

  tracker-search:
    <<: *search-img
    container_name: tracker-search
    restart: always
    ports:
      - "127.0.0.1:9306:9306"
      - "127.0.0.1:9308:9308"
      - "127.0.0.1:9312:9312"
    volumes:
      - manticore-data:/var/lib/manticore/
    networks:
      - tracker-net
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    environment:
      - MCL=1
      - TELEMETRY=0

  tracker-backup:
    <<: *backup-img
    restart: always
    container_name: tracker-backup
    env_file: .env
    entrypoint: ["/app/backup-server"]
    ports:
      - "127.0.0.1:${BACKUP_PORT}:50051"
    volumes:
      - ./data:/app/data:rw
    networks:
      - tracker-net
    healthcheck:
      test: exit 0

  tracker-cache:
    <<: *cache-img
    container_name: tracker-cache
    restart: always
    env_file: .env
    command: >
      --requirepass ${CACHE_PASSWORD}
    networks:
      - tracker-net
    ports:
      - "127.0.0.1:${CACHE_PORT}:6379"
    volumes:
      - cache-volume:/data
    environment:
      REDIS_PASSWORD: ${CACHE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3

  tracker-app:
    <<: *tracker-img
    container_name: tracker-app
    env_file: .env
    restart: always
    depends_on:
      - tracker-db
      - tracker-search
      - tracker-backup
      - tracker-cache
    ports:
       - "127.0.0.1:${API_PORT}:8000"
    entrypoint: ["gunicorn", "tracker.main:app", "--bind", "0.0.0.0:8000", "--workers",
                 "${API_ASGI_WORKERS}", "--worker-class", "uvicorn.workers.UvicornWorker",
                 "--access-logfile", "-", "--error-logfile", "-", "--log-level", "${LOGGER_LEVEL}",
                 "--forwarded-allow-ips", "*"]
    networks:
      - tracker-net
    volumes:
      - ./data:/app/data:rw
      - ./metrics:/app/metrics:rw
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/readiness || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  tracker-prometheus:
    <<: *prometheus-img
    container_name: tracker-prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-volume:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - tracker-net

  tracker-grafana:
    <<: *grafana-img
    container_name: tracker-grafana
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana-volume:/var/lib/grafana
    networks:
      - tracker-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  database-volume:
  manticore-data:
  cache-volume:
  grafana-volume:
  prometheus-volume:

networks:
  tracker-net:
    external: true
