version: '3'

services:
  tracker-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - database-volume:/var/lib/postgresql/data
    container_name: tracker-db
    ports:
      - "0.0.0.0:7432:5432"
    networks:
       - tracker-net
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -q -d ${DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 3

  tracker-search:
    build:
      dockerfile: manticore/Dockerfile
      context: .
    container_name: tracker-search
    restart: always
    ports:
      - "127.0.0.1:9306:9306"
      - "127.0.0.1:9308:9308"
      - "127.0.0.1:9312:9312"
    volumes:
      - manticore-data:/var/lib/manticore/
    networks:
      - tracker-net
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    environment:
      - MCL=1

  reading-tracker:
    image: kunansy/reading_tracker:2.16.12
    container_name: reading-tracker
    env_file: .env
    restart: always
    depends_on:
      - tracker-db
      - tracker-search
    ports:
       - "0.0.0.0:${API_PORT}:8000"
    entrypoint: ["gunicorn", "tracker.main:app", "--bind", "0.0.0.0:8000", "--workers",
                 "${API_ASGI_WORKERS}", "--worker-class", "uvicorn.workers.UvicornWorker",
                 "--access-logfile", "-", "--error-logfile", "-", "--log-level", "${LOGGER_LEVEL}"]
    networks:
      - tracker-net
    volumes:
      - ./data:/app/data 
    healthcheck:
      test: curl -f http://localhost:8000/readiness || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  database-volume:
  manticore-data:

networks:
  tracker-net:
