version: '3'

services:
  tracker-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - database-volume:/var/lib/postgresql/data
    container_name: tracker-db
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    networks:
       - tracker-net
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -q -d ${DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 3

  reading-tracker:
    build: .
    container_name: reading-tracker
    env_file: .env
    restart: always
    depends_on:
      - tracker-db
    ports:
       - "127.0.0.1:${API_PORT}:8000"
    entrypoint: ["uvicorn", "tracker.main:app", "--port", "8000",
                 "--host", "0.0.0.0", "--loop", "uvloop"]
    networks:
      - tracker-net
    healthcheck:
      test: curl -f http://localhost:8000/notes || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  database-volume:

networks:
  tracker-net:
