[tool.poetry]
name = "readingtracker"
version = "1.1.0"
description = "Reading queue, logging the reading, keep some notes"
authors = ["kunansy <kolobov.kirill@list.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
ujson = "~4.2.0"
SQLAlchemy = "~1.4.25"
pydantic = "1.8.2"
environs = "~9.3.4"
types-ujson = "~4.2.0"
types-aiofiles = "~0.7.0"
asyncpg = "~0.24.0"
fastapi = "~0.70.0"
uvicorn = "~0.15.0"
Jinja2 = "~3.0.1"
uvloop = "~0.16.0"
python-multipart = "^0.0.5"
google-api-python-client = "~2.31.0"
google-auth-httplib2 = "~0.1.0"
google-auth-oauthlib = "~0.4.6"

[tool.poetry.dev-dependencies]
flake8 = "~4.0.1"
mypy = "~0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
