[tool.ruff]
line-length = 150
ignore = ["E711","E712"]

target-version = "py311"

[tool.poetry]
name = "readingtracker"
version = "2.19.7"
description = "Reading queue, logging the reading, keep some notes"
authors = ["kunansy <k@kunansy.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
SQLAlchemy = "~2.0.0"
pydantic = "~2.5.2"
environs = "~9.5.0"
asyncpg = "~0.29.0"
fastapi = "~0.104.1"
uvicorn = "~0.24.0.post1"
Jinja2 = "~3.1.1"
uvloop = "~0.19.0"
python-multipart = "~0.0.6"
matplotlib = "~3.8.0"
orjson = "~3.9.1"
types-orjson = "~3.6.2"
gunicorn = "~21.2.0"
aiomysql = "~0.2.0"
aiogoogle = "~5.6.0"
networkx = "~3.1"
pyvis = "0.3.1"
speechrecognition = "~3.10.0"
pyaudio = "~0.2.13"
pydub = "~0.25.1"
uuid6 = "~2023.5.2"
grpcio = "~1.56.0"
grpcio-tools = "~1.56.0"
types-protobuf = "^4.23.0.1"

[tool.poetry.group.dev.dependencies]
mypy = "~1.7.1"
flake8 = "~6.1.0"
bumpversion = "~0.6.0"
greenlet = "~2.0.1"
ruff = "~0.1.6"
pytest = "~7.4.0"
pytest-asyncio = "~0.21.0"
coverage = "~7.3.2"
flake8-async = "^22.11.14"
flake8-warnings = "^0.4.0"
flake8-implicit-str-concat = "^0.4.0"
flake8-print = "^5.0.0"
flake8-use-pathlib = "^0.3.0"
flake8-builtins = "^2.1.0"
flake8-comments = "^0.1.2"
flake8-absolute-import = "^1.0.0.1"
flake8-markdown = "~0.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
