[tool.poetry]
name = "readingtracker"
version = "1.1.0"
description = ""
authors = ["kunansy <kolobov.kirill@list.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
ujson = "4.0.2"
SQLAlchemy = "1.4.18"
sanic = "=21.3.4"
sanic-jinja2 = "0.10.0"
sanic-session = "0.8.0"
pydantic = "1.8.2"
environs = "9.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
