[tool.ruff]
line-length = 150
ignore = ["E711","E712"]

target-version = "py311"

[tool.poetry]
name = "readingtracker"
version = "2.19.7"
description = "Reading queue, logging the reading, keep some notes"
authors = ["kunansy <kolobov.kirill@list.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
SQLAlchemy = "~1.4.36"
pydantic = "~1.10.1"
environs = "~9.5.0"
asyncpg = "~0.27.0"
fastapi = "~0.95.0"
uvicorn = "~0.21.0"
Jinja2 = "~3.1.1"
uvloop = "~0.17.0"
python-multipart = "~0.0.6"
matplotlib = "~3.7.0"
orjson = "~3.8.0"
types-orjson = "~3.6.2"
gunicorn = "~20.1.0"
aiomysql = "^0.1.1"
aiogoogle = "~5.3.0"
networkx = "~3.0"
pyvis = "0.3.1"
speechrecognition = "~3.10.0"
pyaudio = "~0.2.13"
pydub = "~0.25.1"
uuid6 = "^2022.10.25"

[tool.poetry.group.dev.dependencies]
mypy = "~1.2.0"
flake8 = "~6.0.0"
bumpversion = "~0.6.0"
greenlet = "~2.0.1"
ruff = "~0.0.220"
pytest = "~7.3.0"
pytest-asyncio = "~0.21.0"
coverage = "~7.2.0"
flake8-async = "^22.11.14"
flake8-warnings = "^0.4.0"
flake8-implicit-str-concat = "^0.4.0"
flake8-print = "^5.0.0"
flake8-use-pathlib = "^0.3.0"
flake8-builtins = "^2.1.0"
flake8-comments = "^0.1.2"
flake8-absolute-import = "^1.0.0.1"
flake8-markdown = "^0.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
