[tool.poetry]
name = "readingtracker"
version = "2.1.1"
description = "Reading queue, logging the reading, keep some notes"
authors = ["kunansy <kolobov.kirill@list.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
ujson = "~5.2.0"
SQLAlchemy = "~1.4.25"
pydantic = "~1.9.0"
environs = "~9.5.0"
types-ujson = "~4.2.0"
asyncpg = "~0.25.0"
fastapi = "~0.75.0"
uvicorn = "~0.17.5"
Jinja2 = "~3.1.1"
uvloop = "~0.16.0"
python-multipart = "^0.0.5"
google-api-python-client = "~2.31.0"
google-auth-httplib2 = "~0.1.0"
google-auth-oauthlib = "~0.4.6"
greenlet = "~1.1.2"
matplotlib = "~3.5.1"

[tool.poetry.dev-dependencies]
flake8 = "~4.0.1"
mypy = "~0.950"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
