[tool.ruff]
line-length = 90
indent-width = 4
target-version = "py312"
exclude = ["backup_pb2_grpc.py"]
extend-exclude = ["tests"]

[tool.ruff.lint]
select = ["ANN", "B", "C", "E", "F", "I", "Q", "S", "SIM", "UP", "W"]
ignore = [
    "ANN002", "ANN003", "ANN101", "ANN102", "ANN201", "ANN401",
    "C416",
    "E711", "E712",
    "S101", "S110", "SIM108"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
    "fastapi.Depends",
    "fastapi.Query",
    "fastapi.Form",
    "fastapi.Body",
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.pep8-naming]
classmethod-decorators = [
    "pydantic.validator",
    "pydantic.field_validator",
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-wrap-aliases = true
lines-after-imports = 2

[tool.ruff.lint.flake8-annotations]
suppress-none-returning = true

[tool.black]
line-length=90
target-version = ["py312"]
workers = 10
exclude = "protos"

[tool.flake8]
max-line-length = 150
#comparison with None, comparison with bool, line break before/after binary op,
ignore = ["E711", "E712", "W503", "W504"]
exclude = "backup_pb2_grpc.py"
#allow these var/func names
builtins-ignorelist = ["max", "min", "format"]

[tool.mypy]
python_version = 3.12
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "*.schemas.*"
ignore_errors = true

[tool.poetry]
name = "readingtracker"
version = "2.19.7"
description = "Reading queue, logging the reading, keep some notes"
authors = ["kunansy <k@kunansy.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
SQLAlchemy = "~2.0.0"
pydantic = "~2.6.0"
environs = "~10.3.0"
asyncpg = "~0.29.0"
fastapi = "~0.109.0"
uvicorn = "~0.27.0.post1"
Jinja2 = "~3.1.1"
uvloop = "~0.19.0"
python-multipart = "~0.0.6"
matplotlib = "~3.8.0"
orjson = "~3.9.1"
types-orjson = "~3.6.2"
gunicorn = "~21.2.0"
aiomysql = "~0.2.0"
networkx = "~3.1"
pyvis = "0.3.1"
speechrecognition = "~3.10.0"
pyaudio = "~0.2.13"
pydub = "~0.25.1"
uuid6 = "~2024.01.12"
grpcio = "~1.59.0"
grpcio-tools = "~1.59.0"
types-protobuf = "^4.23.0.1"
fastapi-cache2 = {extras = ["redis"], version = "^0.2.1"}
starlette-exporter = "~0.19.0"

[tool.poetry.group.dev.dependencies]
mypy = "~1.8.0"
flake8 = "~7.0.0"
bumpversion = "~0.6.0"
greenlet = "~3.0.1"
ruff = "~0.2.0"
pytest = "~8.0.0"
pytest-asyncio = "~0.23.2"
coverage = "~7.4.0"
flake8-async = "^22.11.14"
flake8-warnings = "^0.4.0"
flake8-implicit-str-concat = "^0.4.0"
flake8-print = "^5.0.0"
flake8-use-pathlib = "^0.3.0"
flake8-builtins = "^2.1.0"
flake8-comments = "^0.1.2"
flake8-absolute-import = "^1.0.0.1"
flake8-markdown = "~0.5.0"
pytest-xdist = "~3.5.0"
black = "~24.1.1"
flake8-pyproject = "~1.2.3"
types-redis = "^4.6.0.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
