[tool.poetry]
name = "readingtracker"
version = "2.12.1"
description = "Reading queue, logging the reading, keep some notes"
authors = ["kunansy <kolobov.kirill@list.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
ujson = "~5.5.0"
SQLAlchemy = "~1.4.25"
pydantic = "~1.10.1"
environs = "~9.5.0"
types-ujson = "~5.5.0"
asyncpg = "~0.26.0"
fastapi = "~0.85.0"
uvicorn = "~0.18.1"
Jinja2 = "~3.1.1"
uvloop = "~0.17.0"
python-multipart = "^0.0.5"
google-api-python-client = "~2.48.0"
google-auth-httplib2 = "~0.1.0"
google-auth-oauthlib = "~0.4.6"
greenlet = "~1.1.2"
matplotlib = "~3.6.0"
aiohttp = "~3.8.1"

[tool.poetry.dev-dependencies]
flake8 = "~5.0.4"
mypy = "~0.971"
bumpversion = "~0.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
