[tool.ruff]
line-length = 150
ignore = ["E711"]

target-version = "py311"

[tool.poetry]
name = "readingtracker"
version = "2.18.3"
description = "Reading queue, logging the reading, keep some notes"
authors = ["kunansy <kolobov.kirill@list.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
SQLAlchemy = "~1.4.36"
pydantic = "~1.10.1"
environs = "~9.5.0"
asyncpg = "~0.27.0"
fastapi = "~0.90.1"
uvicorn = "~0.20.0"
Jinja2 = "~3.1.1"
uvloop = "~0.17.0"
python-multipart = "^0.0.5"
matplotlib = "~3.6.0"
orjson = "~3.8.0"
types-orjson = "~3.6.2"
gunicorn = "~20.1.0"
aiomysql = "^0.1.1"
aiogoogle = "~5.1.0"
networkx = "~3.0"
pyvis = "^0.3.1"

[tool.poetry.group.dev.dependencies]
mypy = "~1.0.0"
flake8 = "~6.0.0"
bumpversion = "~0.6.0"
greenlet = "~2.0.1"
ruff = "~0.0.220"
pytest = "~7.2.1"
pytest-asyncio = "~0.20.3"
coverage = "~7.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
