version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    restart: always
    ports:
      - "127.0.0.1:2181:2181"
      - "127.0.0.1:2888:2888"
      - "127.0.0.1:3888:3888"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./data/zoo/data:/var/lib/zookeeper/data 
      - ./data/zoo/log:/var/lib/zookeeper/log
    networks:
      - tracker-net

  broker:
    image: confluentinc/cp-server:7.6.0
    container_name: broker
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:9092:9092"
      - "127.0.0.1:29093:29093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: "true"
      CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"
    networks:
      - tracker-net

  debezium:
    image: quay.io/debezium/connect:2.5
    restart: always
    container_name: debezium
    ports:
     - "127.0.0.1:8083:8083"
     - "127.0.0.1:8778:8778"
     - "127.0.0.1:39092:9092"
    depends_on:
     - kafka
    environment:
     - BOOTSTRAP_SERVERS=broker:29092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=debezium_config
     - OFFSET_STORAGE_TOPIC=debezium_offsets
     - STATUS_STORAGE_TOPIC=debezium_connect_statuses
    networks:
      - tracker-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    command: ["tail", "-f", "/dev/null"]
    network_mode: "host"
    networks:
      - tracker-net
    volumes:
      - kafka-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "127.0.0.1:8090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT
    networks:
      - tracker-net
    volumes: 
      - ./data/broker:/var/lib/kafka/data

volumes:
  kafka-data:

networks:
  tracker-net:
    external: true
