name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Poetry
      run: |
        pip install pipx
        pipx install poetry

    - name: Validate the pyproject.toml
      run: |
        poetry check

    - name: Verify poetry.lock consistency
      run: |
        poetry lock --check

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root

    - name: Check code by flake8
      run: |
        poetry run flake8

    - name: Check code by mypy
      run: |
        poetry run mypy .
