name: Linters

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        sudo apt-get install -y portaudio19-dev libasound-dev
        pip install pipx
        pipx install poetry

    - name: Validate the pyproject.toml
      run: |
        poetry check

    - name: Verify poetry.lock consistency
      run: |
        poetry lock --check

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-root

    - name: Check code
      run: |
        make lint
